version: '3.1'

services:

  mongo:
    image: mongo
    container_name: todo-mongo-db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"