spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: user
      password: 1234
      database: todo-db

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG